/**
 * mysite.WebAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BlogDto { 
    id?: string;
    title?: string | null;
    content?: string | null;
    createdAt?: string;
    updatedAt?: string;
}

