/**
 * mysite.WebAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectDto { 
    id?: string;
    name?: string | null;
    description?: string | null;
    startDate?: string;
    endDate?: string;
    isCompleted?: boolean;
}

