/**
 * mysite.WebAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateOnly } from './dateOnly';


export interface WeatherForecast { 
    date?: DateOnly;
    temperatureC?: number;
    summary?: string | null;
    readonly temperatureF?: number;
}

